#!/bin/bash

# A simple sketchybar config for aerospace users to get started with
# Not too different from the base starting config!
PLUGIN_DIR="$CONFIG_DIR/plugins"
source "$PLUGIN_DIR/colors.sh"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=bottom height=30 color="$TRANSPARENT"

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font:Bold:15.0"
  label.font="SF Pro:Semibold:13.0"
  icon.color="$TEXT_WHITE"
  label.color="$TEXT_WHITE"
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
  updates=on
  y_offset=-3
)

declare -a space_creator=(
  script="$PLUGIN_DIR/space_windows.sh"
  update_freq=1
)

sketchybar --default "${default[@]}"

sketchybar --add item spacePaddingLeft left --set spacePaddingLeft padding_left=-18

##### Adding aerospace layouts #####
sketchybar --add event aerospace_workspace_change
sketchybar --add event aerospace_monitor_change
sketchybar --add event aerospace_window_change

while read -r screen_id sid; do
	  sketchybar --add item space.$sid left
	  sketchybar --set space.$sid \
	    display="$screen_id" \
	    drawing=off \
	    background.corner_radius=5 \
	    background.drawing=on \
	    background.height=23 \
	    background.padding_right=5 \
	    background.padding_left=5 \
	    icon="$sid" \
	    icon.shadow.drawing=off \
	    icon.padding_left=10 \
	    icon.color="$TEXT_GREY" \
	    label.color="$TEXT_GREY" \
	    label.font="sketchybar-app-font:Regular:13.0" \
	    label.padding_right=20 \
	    label.padding_left=0 \
	    label.y_offset=-1 \
	    label.shadow.drawing=off \
	    click_script="aerospace workspace $sid"
done < <(aerospace list-workspaces --all --format "%{monitor-appkit-nsscreen-screens-id} %{workspace}")

# Load Icons on startup
for mid in $(aerospace list-monitors | cut -c1); do
  for sid in $(aerospace list-workspaces --monitor $mid --empty no); do
    apps=$(aerospace list-windows --workspace "$sid" | awk -F'|' '{gsub(/^ *| *$/, "", $2); print $2}')

    sketchybar --set space.$sid drawing=on

    icon_strip=" "
    if [ "${apps}" != "" ]; then
      while read -r app; do
        icon_strip+=" $($CONFIG_DIR/plugins/icon_map_fn.sh "$app")"
      done <<<"${apps}"
    else
      icon_strip=""
    fi
    sketchybar --set space.$sid label="$icon_strip"
  done
done

# Set color for currently focused space
sketchybar --set space."$(aerospace list-workspaces --focused)" background.color=$HIGHLIGHT_BACKGROUND label.color=$TEXT_WHITE icon.color=$TEXT_WHITE #background.border_color=$TEXT_GREY

sketchybar --add item spacePaddingRight left --set spacePaddingRight padding_left=-18

sketchybar --add item space_separator q \
  --set space_separator icon="" \
  icon.padding_left=20 \
  icon.padding_right=0 \
  label.drawing=on \
  label.padding_left=0 \
  background.drawing=off \
  script="$PLUGIN_DIR/space_windows.sh" \
  --subscribe space_separator aerospace_workspace_change space_windows_change front_app_switched aerospace_monitor_change

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other gititems respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
  --set clock update_freq=10 script="$PLUGIN_DIR/clock.sh" \
  icon.padding_left=0 \
  label.color="$TEXT_WHITE" \
  label.font="alarm clock:Regular:13.0" \
  label.padding_right=20 \
  \
  --add item battery right \
  --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change \
  \
  --add item volume right \
  --set volume script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change \
  \
    --add item btc right \
  --set btc \
  icon= \
  script="$PLUGIN_DIR/btc.sh" \
  update_freq=60 \
  --subscribe btc mouse.clicked  \
  \
  --add item space_creator left               \
  --set space_creator "${space_creator[@]}"   \
  --subscribe space_creator aerospace_workspace_change 
#
  # --add item weather right \
  # --set weather \
  # icon=󰖐 \
  # script="$PLUGIN_DIR/weather.sh" \
  # update_freq=600 \
  # --subscribe weather mouse.clicked \
  # \



sketchybar --hotload on

sketchybar --update
